name: CI

on:
  push:
    tags: 
      - "Versions/AirQualityMonitor/*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: build the image
        run: |
          docker buildx build --push \
            -f "AirQualityMonitor/Dockerfile" \
            --tag devbot9/tinkerforge-airqualitymonitor:${GITHUB_REF#refs/tags/Versions/AirQualityMonitor/} \
            --tag devbot9/tinkerforge-airqualitymonitor:latest \
            --platform linux/amd64,linux/arm/v7,linux/arm64 .
